//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sample.Extensions.Properties.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Parameter {0} darf nicht NULL sein. ähnelt.
        /// </summary>
        public static string ERR_MSG_ARGUMENT_NULL {
            get {
                return ResourceManager.GetString("ERR_MSG_ARGUMENT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Deserialisieren eines Objekts ähnelt.
        /// </summary>
        public static string ERR_MSG_FAILURE_DESERIALIZE {
            get {
                return ResourceManager.GetString("ERR_MSG_FAILURE_DESERIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Serialisieren eines Objektes ähnelt.
        /// </summary>
        public static string ERR_MSG_FAILURE_SERIALIZE {
            get {
                return ResourceManager.GetString("ERR_MSG_FAILURE_SERIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Argument ist nicht gültig ähnelt.
        /// </summary>
        public static string ERR_MSG_INVALID_ARGUMENT {
            get {
                return ResourceManager.GetString("ERR_MSG_INVALID_ARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene MimeType wurde nicht gefunden ähnelt.
        /// </summary>
        public static string ERR_MSG_INVALID_MIME_TYPE {
            get {
                return ResourceManager.GetString("ERR_MSG_INVALID_MIME_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die erforderliche Berechtigungen sind nicht vorhanden ähnelt.
        /// </summary>
        public static string ERR_MSG_MISSING_RIGHTS {
            get {
                return ResourceManager.GetString("ERR_MSG_MISSING_RIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für den angegebenen ContentType wurde kein MimeType gefunden ähnelt.
        /// </summary>
        public static string ERR_MSG_NO_MIME_FOR_CONTENT_TYPE {
            get {
                return ResourceManager.GetString("ERR_MSG_NO_MIME_FOR_CONTENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für die angegebene Dateiendung wurde kein MimeType gefunden, Dateiendung:  ähnelt.
        /// </summary>
        public static string ERR_MSG_NO_MIME_FOR_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("ERR_MSG_NO_MIME_FOR_FILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Serialisieren der Fields nach JSON ähnelt.
        /// </summary>
        public static string ERR_MSG_SERIALIZE_JSON_FILEDS {
            get {
                return ResourceManager.GetString("ERR_MSG_SERIALIZE_JSON_FILEDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Serialisieren der Properties nach JSON ähnelt.
        /// </summary>
        public static string ERR_MSG_SERIALIZE_JSON_PROPERTIES {
            get {
                return ResourceManager.GetString("ERR_MSG_SERIALIZE_JSON_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vom Stream kann nicht gelesen werden. ähnelt.
        /// </summary>
        public static string ERR_MSG_STREAM_CANREAD {
            get {
                return ResourceManager.GetString("ERR_MSG_STREAM_CANREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation wurde wegen Timeout abgebrochen ähnelt.
        /// </summary>
        public static string ERR_MSG_TIMEOUT {
            get {
                return ResourceManager.GetString("ERR_MSG_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl Fehler pro Sekunde ähnelt.
        /// </summary>
        public static string EVENT_COUNTER_EXCEPTION_PER_SECOND_DESCRIPTION {
            get {
                return ResourceManager.GetString("EVENT_COUNTER_EXCEPTION_PER_SECOND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ausgelöste nicht-kategorisierte Fehler/s ähnelt.
        /// </summary>
        public static string EVENT_COUNTER_NON_CATEGORIZED_EXCEPTION_PER_SECOND_DESCRIPTION {
            get {
                return ResourceManager.GetString("EVENT_COUNTER_NON_CATEGORIZED_EXCEPTION_PER_SECOND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei der Vorgangsverarbeitung. ähnelt.
        /// </summary>
        public static string OP_RESULT_FAILURE {
            get {
                return ResourceManager.GetString("OP_RESULT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang nicht notwendig. ähnelt.
        /// </summary>
        public static string OP_RESULT_NOT_REQUIRED {
            get {
                return ResourceManager.GetString("OP_RESULT_NOT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Funktion wurde erfolgreich ausgeführt. ähnelt.
        /// </summary>
        public static string OP_RESULT_SUCCESSFUL_DONE {
            get {
                return ResourceManager.GetString("OP_RESULT_SUCCESSFUL_DONE", resourceCulture);
            }
        }
    }
}
